"""Perf Review Agent + Jira MCP Integration.

Demonstrates:
- Creating defect tickets for performance findings
- Linking defects to the source story/epic
- Adding detailed findings as comments
- Updating defect status after verification
"""

from .jira_mcp_client import JiraMCPClient


class PerfReviewJiraIntegration:
    """Connects the Performance Review Agent with Jira defect tracking via MCP."""

    SEVERITY_TO_PRIORITY = {
        "CRITICAL": "Highest",
        "HIGH": "High",
        "MEDIUM": "Medium",
        "LOW": "Low",
    }

    def __init__(self, jira: JiraMCPClient, project_key="PERF"):
        self.jira = jira
        self.project_key = project_key

    def create_perf_defect(self, finding):
        """Create a Jira defect ticket from a performance finding.

        Args:
            finding: dict with keys: title, severity, category, file, line,
                     issue, impact, current_code, recommended_fix, estimated_impact
        """
        severity = finding.get("severity", "MEDIUM")
        category = finding.get("category", "UNKNOWN")
        file_path = finding.get("file", "unknown")
        line = finding.get("line", "")

        summary = f"[PERF-{severity}] {finding['title']}"

        description_lines = [
            f"Category: {category}",
            f"Severity: {severity}",
            f"File: {file_path}:{line}",
            "",
            "Issue:",
            finding.get("issue", ""),
            "",
            "Production Impact:",
            finding.get("impact", ""),
            "",
            "Current Code:",
            "{{code}}",
            finding.get("current_code", ""),
            "{{code}}",
            "",
            "Recommended Fix:",
            "{{code}}",
            finding.get("recommended_fix", ""),
            "{{code}}",
            "",
            f"Estimated Impact: {finding.get('estimated_impact', '')}",
            "",
            "---",
            "Generated by Performance Review Agent",
        ]

        description = "\n".join(description_lines)
        priority = self.SEVERITY_TO_PRIORITY.get(severity, "Medium")

        return self.jira.create_issue(
            project_key=self.project_key,
            issue_type="Bug",
            summary=summary,
            description=description,
            priority=priority
        )

    def create_defects_from_scan(self, findings, source_ticket=None):
        """Create defect tickets for all findings from a performance scan.

        Args:
            findings: list of finding dicts
            source_ticket: optional ticket key to reference in comments

        Returns:
            list of created ticket keys
        """
        created_tickets = []

        for finding in findings:
            result = self.create_perf_defect(finding)
            ticket_key = result.get("key", "")
            created_tickets.append(ticket_key)

            if source_ticket and ticket_key:
                self.jira.add_comment(
                    source_ticket,
                    f"Performance defect created: {ticket_key} - {finding['title']}"
                )

        return created_tickets

    def search_open_perf_defects(self, max_results=20):
        """Find open performance defects."""
        jql = (
            f'project = {self.project_key} '
            f'AND issuetype = Bug '
            f'AND summary ~ "PERF-" '
            f'AND status != Done'
        )
        return self.jira.search_issues(jql, max_results)

    def close_defect(self, ticket_key, resolution_comment):
        """Close a performance defect with resolution details."""
        self.jira.add_comment(ticket_key, f"Resolution: {resolution_comment}")
        return self.jira.update_issue_status(ticket_key, "Done")

    def add_scan_summary(self, ticket_key, scan_results):
        """Add a performance scan summary as a comment."""
        total = len(scan_results.get("findings", []))
        by_severity = {}
        for f in scan_results.get("findings", []):
            sev = f.get("severity", "UNKNOWN")
            by_severity[sev] = by_severity.get(sev, 0) + 1

        lines = [
            "Performance Scan Summary",
            "=" * 40,
            f"Total Findings: {total}",
            "",
            "By Severity:",
        ]
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            if sev in by_severity:
                lines.append(f"  {sev}: {by_severity[sev]}")

        lines.extend([
            "",
            "By Category:",
        ])
        by_category = {}
        for f in scan_results.get("findings", []):
            cat = f.get("category", "UNKNOWN")
            by_category[cat] = by_category.get(cat, 0) + 1
        for cat, count in sorted(by_category.items()):
            lines.append(f"  {cat}: {count}")

        lines.append("\nGenerated by Performance Review Agent")

        return self.jira.add_comment(ticket_key, "\n".join(lines))
