"""Web Test Generation Agent + Jira MCP Integration.

Demonstrates:
- Reading test case descriptions from Jira tickets
- Extracting test steps from Jira issue fields
- Posting generated test script references back to tickets
- Creating test execution tickets
"""

from .jira_mcp_client import JiraMCPClient


class TestGenJiraIntegration:
    """Connects the Web Test Generation Agent with Jira test management via MCP."""

    def __init__(self, jira: JiraMCPClient, project_key="QA"):
        self.jira = jira
        self.project_key = project_key

    def fetch_test_cases(self, sprint=None, component=None, max_results=50):
        """Search for test case tickets to generate scripts from.

        Args:
            sprint: optional sprint name to filter by
            component: optional component to filter by
        """
        jql = f'project = {self.project_key} AND issuetype = "Test Case"'
        if sprint:
            jql += f' AND sprint = "{sprint}"'
        if component:
            jql += f' AND component = "{component}"'
        jql += ' AND status = "Ready for Automation"'

        return self.jira.search_issues(jql, max_results)

    def get_test_steps(self, ticket_key):
        """Extract test steps from a Jira test case ticket.

        Returns structured test step data for script generation.
        """
        issue = self.jira.get_issue(ticket_key)
        fields = issue.get("fields", {})

        test_data = {
            "ticket_key": ticket_key,
            "summary": fields.get("summary", ""),
            "description": fields.get("description", ""),
            "priority": fields.get("priority", {}).get("name", "Medium"),
            "component": "",
            "labels": fields.get("labels", []),
            "steps": [],
        }

        components = fields.get("components", [])
        if components:
            test_data["component"] = components[0].get("name", "")

        description = fields.get("description", "")
        if description:
            test_data["steps"] = self._parse_steps(description)

        return test_data

    def _parse_steps(self, description):
        """Parse numbered test steps from ticket description."""
        steps = []
        lines = description.split("\n")

        for line in lines:
            line = line.strip()
            if not line:
                continue

            for prefix_len in range(1, 4):
                prefix = line[:prefix_len]
                if prefix.rstrip(".").rstrip(")").isdigit() and len(line) > prefix_len:
                    step_text = line[prefix_len:].lstrip(".").lstrip(")").lstrip(" ")
                    if step_text:
                        action = "verify" if any(
                            w in step_text.lower()
                            for w in ["verify", "check", "confirm", "assert", "validate"]
                        ) else "action"
                        steps.append({
                            "step_number": len(steps) + 1,
                            "text": step_text,
                            "type": action
                        })
                    break

        return steps

    def post_generated_script(self, ticket_key, framework, script_path):
        """Post a comment linking the generated test script to the ticket."""
        comment = (
            f"Test script generated ({framework})\n\n"
            f"Script: {script_path}\n"
            f"Framework: {framework}\n\n"
            f"Generated by Web Test Generation Agent"
        )
        return self.jira.add_comment(ticket_key, comment)

    def update_automation_status(self, ticket_key, status="Automated"):
        """Update test case status after script generation."""
        return self.jira.update_issue_status(ticket_key, status)

    def create_test_execution_ticket(self, test_tickets, sprint=None):
        """Create a test execution ticket linking to generated test cases."""
        test_list = "\n".join(f"- {t}" for t in test_tickets)

        summary = f"Test Execution - {len(test_tickets)} automated test cases"
        description = (
            f"Automated test cases for execution:\n\n"
            f"{test_list}\n\n"
            f"Scripts generated by Web Test Generation Agent"
        )

        return self.jira.create_issue(
            project_key=self.project_key,
            issue_type="Test Execution",
            summary=summary,
            description=description
        )

    def bulk_generate_from_jira(self, sprint=None, component=None):
        """Fetch all ready test cases and return structured data for generation.

        Returns a list of test case data dicts ready for the
        Web Test Generation Agent to process.
        """
        tickets = self.fetch_test_cases(sprint=sprint, component=component)
        issues = tickets.get("issues", [])

        test_cases = []
        for issue in issues:
            key = issue.get("key", "")
            test_data = self.get_test_steps(key)
            if test_data["steps"]:
                test_cases.append(test_data)

        return test_cases
